{% set name = "opcua" %}
{% set version = "0.98.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 947cf0de842f9eee86ed2c39607c2b2c5a288ed42e0298d87c7a663ec7ee48aa

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - uabrowse = opcua.tools:uals
    - uacall = opcua.tools:uacall
    - uaclient = opcua.tools:uaclient
    - uadiscover = opcua.tools:uadiscover
    - uahistoryread = opcua.tools:uahistoryread
    - uals = opcua.tools:uals
    - uaread = opcua.tools:uaread
    - uaserver = opcua.tools:uaserver
    - uasubscribe = opcua.tools:uasubscribe
    - uawrite = opcua.tools:uawrite

requirements:
  host:
    - python
    - pip
  run:
    - cryptography
    - enum34          # [py2k]
    - futures         # [py2k]
    - lxml
    - python
    - python-dateutil
    - pytz
    - trollius        # [py2k]

test:
  imports:
    - opcua
    - opcua.client
    - opcua.common
    - opcua.crypto
    - opcua.server
    - opcua.ua
  commands:
    - uabrowse -h
    - uacall -h
    - uaclient -h
    - uadiscover -h
    - uahistoryread -h
    - uals -h
    - uaread -h
    - uaserver -h
    - uasubscribe -h
    - uawrite -h

about:
  home: http://freeopcua.github.io/
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING
  summary: LGPL Pure Python OPC-UA Client and Server
  doc_url: https://python-opcua.readthedocs.io
  dev_url: https://github.com/FreeOpcUa/python-opcua

extra:
  recipe-maintainers:
    - m-rossi
